"""empty message

Revision ID: edc3aa18f8ff
Revises: None
Create Date: 2016-08-04 23:53:05.841858

"""

# revision identifiers, used by Alembic.
revision = 'edc3aa18f8ff'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('googleplaceraw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('googleplaceraw')
    ### end Alembic commands ###
